version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Build
          command: |
            make build && cp function.zip /tmp/function.zip

      - store_artifacts:
          path: /tmp/function.zip
          destination: function.zip
